<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:property name="base_length" value="0.6" />

    <xacro:macro name="wheel_link" params="name">
        <link name="${name}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${base_length / 6.0}" length="${base_length / 12.0}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${base_length / 6.0}" length="${base_length / 12.0}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            </collision>
            <inertial>
                <mass value="0.5"/>
                <inertia ixx="0.001" iyy="0.001" izz="0.001" ixy="0.0" ixz="0.0" iyz="0.0"/>
            </inertial>
        </link>
    </xacro:macro>

    <xacro:wheel_link name="left"/>
    <xacro:wheel_link name="right"/>

    <link name="base_footprint"/>

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_length / 1.5} ${base_length / 3.0}"/>
            </geometry>
            <origin xyz="0 0 ${base_length / 6.0}" rpy="0 0 0"/>
            <material name="blue" />
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_length / 1.5} ${base_length / 3.0}"/>
            </geometry>
            <origin xyz="0 0 ${base_length / 6.0}" rpy="0 0 0"/>
        </collision>
        <inertial>
            <mass value="5.0"/>
            <inertia ixx="0.1" iyy="0.1" izz="0.1" ixy="0.0" ixz="0.0" iyz="0.0"/>
        </inertial>
    </link>

    <link name="castor_wheel_link">
        <visual>
            <geometry>
                <sphere radius="${base_length / 12.0}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </visual>
        <collision>
            <geometry>
                <sphere radius="${base_length / 12.0}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <inertial>
            <mass value="0.2"/>
            <inertia ixx="0.0001" iyy="0.0001" izz="0.0001" ixy="0.0" ixz="0.0" iyz="0.0"/>
        </inertial>
    </link>

</robot>
