<?xml version="1.0"?>
<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:property name="base_length" value="0.6" />

    <material name="blue">
        <color rgba="0 0 0.6 1" />
    </material>

    <link name="base_footprint" />

    <link name="base_link">
        <visual>
            <geometry>
                <box size="${base_length} ${base_length / 1.5} ${base_length / 3.0}"/>
            </geometry>
            <origin xyz="0 0 ${base_length / 6.0}" rpy="0 0 0"/>
            <material name="blue" />
        </visual>
    </link>

    <link name="right_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${base_length / 6.0}" length="${base_length / 12.0}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
        </visual>
    </link>

    <link name="left_wheel_link">
        <visual>
            <geometry>
                <cylinder radius="${base_length / 6.0}" length="${base_length / 12.0}" />
            </geometry>
            <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
        </visual>
    </link>

    <link name="castor_wheel_link">
        <visual>
            <geometry>
                <sphere radius="${base_length / 12.0}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </visual>
    </link>

    <joint name="base_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_wheel_link" />
        <origin xyz="${-base_length / 4.0} ${base_length / 2.55} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_left_wheel_link" type="continuous">
        <parent link="base_link" />
        <child link="left_wheel_link" />
        <origin xyz="${-base_length / 4.0} ${-base_length / 2.55} 0" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="base_castor_wheel_link" type="fixed">
        <parent link="base_link" />
        <child link="castor_wheel_link" />
        <origin xyz="${base_length / 3.0} 0 ${-base_length / 13.3}" rpy="0 0 0" />
    </joint>

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 0.1" rpy="0 0 0" />
    </joint>


    <!-- <joint name="base_second_joint" type="continuous">
        <parent link="base_link" />
        <child link="second_link" />
        <origin xyz="0 0 0.2" rpy="0 0 0" />
        <axis xyz="0 0 1" />
    </joint> -->

    <!-- <joint name="base_second_joint" type="prismatic">
        <parent link="base_link" />
        <child link="second_link" />
        <origin xyz="0 0 0.2" rpy="0 0 0" />
        <axis xyz="1 0 0" />
        <limit lower="0.0" upper="0.5" velocity="100" effort="100" />
    </joint> -->

</robot>    